// lib/widgets/add_income.dart

import 'package:flutter/material.dart';
import 'package:intl/intl.dart'; // For date formatting
import 'package:expense_tracker/comonFunctions.dart';
import 'package:expense_tracker/models/income_model.dart'; // Adjust to your actual model path
import 'package:expense_tracker/services/income_service.dart'; // Adjust to your actual service path

class AddIncome extends StatefulWidget {
  final VoidCallback onClose;
  final VoidCallback onSuccess;

  AddIncome({required this.onClose, required this.onSuccess});

  @override
  _AddIncomeState createState() => _AddIncomeState();
}

class _AddIncomeState extends State<AddIncome> {
  final _formKey = GlobalKey<FormState>();
  final _amountController = TextEditingController();
  final _dateController = TextEditingController();
  final _noteController = TextEditingController();

  String _selectedCategory = '';
  DateTime _date = DateTime.now();
  String _note = '';
  bool _recurring = false;
  String _error = '';

  final List<String> _categories = [
    'Category 1',
    'Category 2',
    'Category 3'
    // Add actual categories here
  ];

  @override
  void initState() {
    super.initState();
    _dateController.text = DateFormat('yyyy-MM-dd').format(_date);
  }

  void _handleCategoryChange(String? value) {
    setState(() {
      _selectedCategory = value ?? '';
    });
  }

  void _handleAmountChange(String value) {
    // No need to update state for amount directly
  }

  void _handleDateChange(DateTime value) {
    setState(() {
      _date = value;
      _dateController.text = DateFormat('yyyy-MM-dd').format(value);
    });
  }

  void _handleNoteChange(String value) {
    setState(() {
      _note = value;
    });
  }

  void _handleRecurringChange(bool? value) {
    setState(() {
      _recurring = value ?? false;
    });
  }

  void _handleSubmit() async {
    if (_formKey.currentState?.validate() ?? false) {
      try {
        final userId = await getUserId();
        if (userId != null) {
          final income = Income(
            id: '', // Assuming id will be generated by the server
            amount: double.tryParse(_amountController.text) ?? 0.0,
            category: _selectedCategory,
            date: _date,
            note: _note,
            recurring: _recurring,
            userId: userId,
          );

          final incomeService = IncomeService();
          await incomeService.createIncome(income);

          widget.onSuccess();
          widget.onClose(); // Close the form after submission
        } else {
          setState(() {
            _error = 'Failed to get user ID from token.';
          });
        }
      } catch (e) {
        setState(() {
          _error = 'Failed to create income: ${e.toString()}';
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Add Income'),
        actions: [
          IconButton(
            icon: Icon(Icons.close),
            onPressed: widget.onClose,
          )
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _amountController,
                decoration: InputDecoration(
                  labelText: 'Amount',
                ),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter an amount';
                  }
                  if (double.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              SizedBox(height: 16),
              DropdownButtonFormField<String>(
                value: _selectedCategory.isEmpty ? null : _selectedCategory,
                decoration: InputDecoration(
                  labelText: 'Category',
                ),
                items: _categories.map((category) {
                  return DropdownMenuItem<String>(
                    value: category,
                    child: Text(category),
                  );
                }).toList(),
                onChanged: _handleCategoryChange,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please select a category';
                  }
                  return null;
                },
              ),
              SizedBox(height: 16),
              TextFormField(
                controller: _dateController,
                decoration: InputDecoration(
                  labelText: 'Date',
                ),
                keyboardType: TextInputType.datetime,
                onTap: () async {
                  FocusScope.of(context).requestFocus(FocusNode());
                  final selectedDate = await showDatePicker(
                    context: context,
                    initialDate: _date,
                    firstDate: DateTime(2000),
                    lastDate: DateTime(2101),
                  );
                  if (selectedDate != null && selectedDate != _date) {
                    _handleDateChange(selectedDate);
                  }
                },
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter a date';
                  }
                  return null;
                },
              ),
              SizedBox(height: 16),
              TextFormField(
                controller: _noteController,
                decoration: InputDecoration(
                  labelText: 'Note',
                ),
                maxLines: 3,
                onChanged: _handleNoteChange,
              ),
              SizedBox(height: 16),
              Row(
                children: [
                  Checkbox(
                    value: _recurring,
                    onChanged: _handleRecurringChange,
                  ),
                  Text('Recurring'),
                ],
              ),
              SizedBox(height: 16),
              ElevatedButton(
                onPressed: _handleSubmit,
                child: Text('Add Income'),
              ),
              if (_error.isNotEmpty)
                Padding(
                  padding: const EdgeInsets.only(top: 16.0),
                  child: Text(
                    _error,
                    style: TextStyle(color: Colors.red),
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}
